name: Build Windows Executable

on:
    workflow_dispatch:
    push:
      branches: [ main ]

jobs:
    build-windows:
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyInstaller>=5.0.0

      - name: Build executable
        run: |
          pyinstaller --onefile --console --name="BeidouMonitor" --add-data="index.html;." --hidden-import=cryptography  --hidden-import=cryptography.hazmat --hidden-import=cryptography.hazmat.primitives --hidden-import=cryptography.hazmat.primitives.kdf  --collect-all=cryptography --collect-all=oracledb app_launcher_fixed.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: BeidouMonitor-exe
          path: dist/BeidouMonitor.exe
          retention-days: 30
